// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package animeDb

import (
	"encoding/json"
)

type Animemapping struct {
	ID           int32
	Anilistid    int32
	Plexseriesid string
}

type Animeresultcache struct {
	ID       int32
	Response json.RawMessage
}

type Animesearchcache struct {
	ID         int32
	Searchterm string
	Response   json.RawMessage
}
