// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package animeDb

import (
	"encoding/json"
)

type Animeresultcache struct {
	ID       int32
	Response json.RawMessage
}

type Animesearchcache struct {
	ID         int64
	Searchterm string
	Response   json.RawMessage
}
